### PR TITLE
Message validation in changed.

### LINKED ISSUE #12: If DTO does not accept all keys of only function from queue, does DTO need to throw validation error ?

### PR DESCRIPTION
**Pull request by usmonaliyev99**
I have checked that in both two mode.
Let's check code, if there is problem, i will change it.

### CODE REVIEW

**Comment by usmonaliyev99** [comment]
What do you think about error of Codacy Static Cod eAnalysis

**Comment by sobirjonovs** [comment]
> What do you think about error of Codacy Static Cod eAnalysis

If you meant the security issue in codacy analysis tool, it is not critical as codacy showed.

**Comment by sobirjonovs** [comment]
I will test your code, then merge it. Thank you for your contribution!

**Comment by usmonaliyev99** [comment]
> > If you meant the security issue in codacy analysis tool, it is not critical as codacy showed.
> 
> 
I had changed some code in previous commit, if i know that, i wouldn't change it

**Comment by usmonaliyev99** [comment]
Should I fix that issue ?

**Comment by sobirjonovs** [comment]
> Should I fix that issue ?

Hi, no everything is good. Just, I couldn't check it so that  I have had a problem with my laptop. I will check it and merge it.

**Pull request merged**
