### PR TITLE
fix: composer::autoDiscover problem

### PR DESCRIPTION
**Pull request by usmonaliyev99**

### CODE REVIEW

**Comment by sobirjonovs** [comment]
Hi, where is the problem?

**Comment by usmonaliyev99** [comment]
There is still problem with installing.

**Comment by usmonaliyev99** [comment]
What do you think about it ?

Let's open new project and install this package.

**Comment by usmonaliyev99** [comment]
I have created new package which is usmonaliyev/laravel-rabbit. It is copy of this project. It works good. You can add this changes.

**Comment by usmonaliyev99** [comment]
Yo'q buni bir oz oldin yopib yubordim. Qo'shib yubormang.

**Comment by sobirjonovs** [comment]
> Yo'q buni bir oz oldin yopib yubordim. Qo'shib yubormang.
> 

Qo'shib bo'ldim. Xatosi yo'q edi shekilli?

**Comment by usmonaliyev99** [comment]
Xatosi yo'q. Lekin composer.json ham o'zgartirib yuborilgan edi.

**Comment by sobirjonovs** [comment]
> Xatosi yo'q. Lekin composer.json ham o'zgartirib yuborilgan edi.

O'zgartirdim. Keling telegramda guruh ochib qo'yaylik undan ko'ra?

**Comment by usmonaliyev99** [comment]
> > Xatosi yo'q. Lekin composer.json ham o'zgartirib yuborilgan edi.
> 
> O'zgartirdim. Keling telegramda guruh ochib qo'yaylik undan ko'ra?

Qo'shilaman.

**Comment by usmonaliyev99** [comment]
https://t.me/t1nnur is me.

Guruhga qo'shib qo'yarsiz.

**Comment by sobirjonovs** [comment]
> https://t.me/t1nnur is me.
> 
> Guruhga qo'shib qo'yarsiz.

Sizga yozdim lichkayzga linkni

**Pull request merged**
